---
- name: add public keys
  apt_key:
    url: "{{ packetfence_install__apt_key_url }}"
    state: present
    
# Add packefence repo into sources list dir using specified filename.
- name: install packetfence.list in {{ packetfence_install__deb_sources_dir }}
  template:
    src: packetfence.list.j2
    dest: "{{ packetfence_install__deb_sources_dir }}/packetfence.list"

# to take new key and repo(s) into account
- name: Update apt-cache
  apt:
    update_cache: yes

# Only one package
- name: Install PacketFence from the repo
  apt:
    name: "{{ packetfence_install__deb_packages }}"
    state: "{{ packetfence_install__pkg_state }}"
  register: packetfence_install__register_packages

- name: Install replication tools
  ansible.builtin.apt:
    name: "{{ packetfence_install__deb_replication_pkgs }}"
    state: "{{ packetfence_install__pkg_state }}"
  when: packetfence_install__cluster
