---
- name: Generate PacketFence config files
  template:
    src: 'usr/local/pf/conf/template.conf.j2'
    dest: '{{ packetfence_install__conf_dir }}/{{ item.name }}'
    mode: 0664
    owner: "{{ packetfence_install__user }}"
    group: "{{ packetfence_install__group }}"
  loop: '{{ packetfence_install__configuration }}'

- name: configure fingerbank API key
  ini_file:
    path: "{{ packetfence_install__fingerbank_conf_dir }}/fingerbank.conf"
    section: 'upstream'
    option: 'api_key'
    value: "{{ packetfence_install__fingerbank_setting['upstream']['api_key'] }}"
    mode: 0660
    owner: "{{ packetfence_install__fingerbank_user }}"
    group: "{{ packetfence_install__fingerbank_group }}"
    no_extra_spaces: yes
  when: packetfence_install__fingerbank_setting['upstream']['api_key']
  notify: restart packetfence-fingerbank-collector service
  no_log: True

# to take new DB password into account
- name: restart packetfence-config service
  service:
    name: packetfence-config
    state: restarted
  when: (packetfence_install__register_mininal_config_db_pwd or packetfence_install__register_mininal_config_pfconfig_pwd) is changed
