---
- name: update admin password in db through pfperl-api
  command:
  args:
    argv:
      - "{{ packetfence_install__perlapi_cmd }}"
      - get
      - "-M"
      - PATCH
      - "/{{ packetfence_install__api_user }}/{{ packetfence_install__admin_user['pid'] }}/password"
      - "-c"
      - "{{ packetfence_install__admin_user | to_json }}"
  register: packetfence_install__register_post_config_admin_pwd
  # failed when status is different from 200
  # pfperl-api always return rc=0
  failed_when: (packetfence_install__register_post_config_admin_pwd['stdout'] | from_json ).status != 200

- name: fix permissions on pf files
  command: "{{ packetfence_install__pfcmd }} fixpermissions"
  when: packetfence_install__register_packages is changed

- name: clear the backend of pfconfig
  command: "{{ packetfence_install__pfcmd }} pfconfig clear_backend"
  when: packetfence_install__register_packages is changed

- name: restart packetfence-config service
  service:
    name: packetfence-config
    state: restarted
  when: packetfence_install__register_packages is changed

- name: restart pf services
  command: "{{ packetfence_install__pfcmd }} service pf restart"
  when: packetfence_install__register_packages is changed
