---
- name: Get packages installed
  package_facts:
    manager: 'rpm'

- name: Disable EPEL repositories enabled if epel-release installed
  ini_file:
     path: '/etc/yum.repos.d/{{ item }}.repo'
     section: '{{ item }}'
     option: 'enabled'
     value: '0'
  loop:
    - epel
    - epel-modular
  when: "'epel-release' in ansible_facts.packages"
     
- name: Install package to use ansible mysql_user module
  yum:
    name: "{{ packetfence_install__centos_python_mysql_pkg }}"
    enablerepo: epel
    state: present
    update_cache: yes

- name: Install GPG key
  rpm_key:
    key: "{{ packetfence_install__rpm_key_url }}"
    state: present

- name: Install the PacketFence repo
  yum:
    name: "{{ packetfence_install__centos_release_rpm }}"
    state: present

- name: Install PacketFence package from the repo
  yum:
    name: "{{ packetfence_install__centos_packages }}"
    enablerepo: "{{ packetfence_install__centos['repos'] }}"
    state: "{{ packetfence_install__pkg_state }}"
    update_cache: yes
  register: packetfence_install__register_packages

- name: Install replication tools
  ansible.builtin.yum:
    name: "{{ packetfence_install__rpm_replication_pkgs }}"
    enablerepo: "{{ packetfence_install__centos['repos'] | omit }}"
    state: "{{ packetfence_install__pkg_state }}"
  when: packetfence_install__cluster
