---
- name: add epel repository disabled
  yum_repository:
     name: epel
     description: EPEL YUM repo
     baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
     enabled: no
     gpgcheck: no
     
- name: install package to use ansible mysql_user module
  yum:
    name: "{{ packetfence_install__centos_python_mysql_pkg }}"
    enablerepo: epel
    state: present
    update_cache: yes
    
- name: Install the PacketFence repo
  yum:
    name: "{{ packetfence_install__centos_release_rpm }}"
    state: present

- name: Install PacketFence package from the repo
  yum:
    name: "{{ packetfence_install__centos_packages }}"
    enablerepo: "{{ packetfence_install__centos['repos'] }}"
    state: "{{ packetfence_install__pkg_state }}"
    update_cache: yes
  register: packetfence_install__register_packages
