stages:
  - test

kitchen_centos7:
  stage: test
  # run job only on master branch
  only:
    - master
  script:
    - kitchen test pfinstall-centos-7
  tags:
    - futura

kitchen_debian9:
  stage: test
  # run job only on master branch
  only:
    - master
  script:
    - kitchen test pfinstall-debian-9
  tags:
    - futura
