---
driver:
  name: docker

platforms:
  - name: centos-7
    driver_config:
      platform: centos
      require_chef_omnibus: false # don't install chef in containers
      use_sudo: true # docker commands use sudo (necessary for local socket)
      run_command: /usr/lib/systemd/systemd
      privileged: true
      forward: 1443:1443
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
      
  - name: debian-9
    driver_config:
      image: geerlingguy/docker-debian9-ansible
      platform: debian
      require_chef_omnibus: false # don't install chef in containers
      use_sudo: true # docker commands use sudo (necessary for local socket)
      run_command: /bin/systemd
      privileged: true
      forward: 2443:1443 # forward public port 2443 to 1443
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible_playbook
  hosts: test-kitchen # add 'test-kitchen' host in inventory file
  require_chef_for_busser: false # don't install Chef for Busser tests
  
verifier:
  name: inspec
  sudo: false

suites:
  # use test/integration/{suite_name}/default.yml playbook by default
  - name: pf.common
  - name: pf.install
    # # use local profile
    # verifier:
    #   inspec_tests:
    #     - name: pf-install profile
    #       path: test/integration/pf.install/pf-install/
      