---
- hosts: standalones
  name: install pf on standalones
  become: True
  roles:
    - role: pf.install

# - hosts: clusters
#   name: install pf on clusters
#   become: True
#   roles:
#     - role: pf.cluster

