---
centos_pf_release_pkg: packetfence-release
centos_pf_release_rpm: "http://packetfence.org/downloads/PacketFence/RHEL7/x86_64/RPMS/{{ centos_pf_release_pkg }}-1.2-7.el7.noarch.rpm"
centos_pf_packages:
  - packetfence
  - packetfence-ntlm-wrapper