---
- name: add epel repository disabled
  yum_repository:
     name: epel
     description: EPEL YUM repo
     baseurl: "{{ packetfence_dev__centos_epel_url }}"
     enabled: no
     gpgcheck: no
     
- name: install centos build dependencies
  yum:
    name: "{{ packetfence_dev__centos_build_pkgs }}"
    state: latest
    enablerepo: epel

- name: install utils
  yum:
    name: "{{ packetfence_dev__centos_utils_pkgs }}"
    state: present
    enablerepo: epel
    