---
# defaults file for wpasupplicant
wpasupplicant__pkg_name: 'wpasupplicant'
wpasupplicant__pkg_update_cache: 'no'
wpasupplicant__conf_dir: '/etc/wpa_supplicant'

wpasupplicant__configs:

  - dir: '{{ wpasupplicant__conf_dir }}/eap_tls'
    filename: 'eap_tls.conf'

  - dir: '{{ wpasupplicant__conf_dir }}/eap_peap'
    filename: 'eap_peap_mschapv2.conf'

### eap_tls template variables
wpasupplicant__eap_tls_private_key_passwd: 'whatever'

### eap_peap_mschapv2 template variables
wpasupplicant__eap_peap_mschapv2_identity: 'inverse'
wpasupplicant__eap_peap_mschapv2_password: 'secret'
