---
# tasks file for pf.common
- name: import distribution specific variables
  include_vars: "{{ ansible_os_family|lower }}.yml"

# include in place of import (dynamic evaluation)
- name: include distribution specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: ensure iproute package is installed for next task
  package:
    name: "{{ iproute_pkg }}"
    state: present
  register: iproute_install

- name: recall setup module to refresh facts
  setup:
    filter: ansible_default_ipv4*
  when: iproute_install is changed
    
- name: ensure management IP is in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address }} {{ ansible_hostname }} {{ ansible_nodename }}'
    line: '{{ ansible_default_ipv4.address }} {{ ansible_hostname }} {{ ansible_nodename }}'