---
galaxy_info:
  author: "Inverse inc <info@inverse.ca>"
  description: "Install wpasupplicant and generate configs"
  company: "Inverse inc"
  license: "GPL-3.0-only"
  min_ansible_version: 2.8

  platforms:
    - name: Debian
      versions:
        - buster

  galaxy_tags:
    - wpasupplicant

dependencies: []
