---
galaxy_info:
  author: "Inverse inc <info@inverse.ca>"
  description: "Install Venom"
  company: "Inverse inc"
  license: "GPL-3.0-only"
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - venom
    - ovh

dependencies: []
