# meta file
---
galaxy_info:
  author: "Inverse inc <info@inverse.ca>"
  description: Manages rc-local in Debian-like systems
  company: "Inverse inc"
  license: MIT
  min_ansible_version: 2.9.0

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster

  galaxy_tags:
    - system

dependencies: []
