---
# tasks file for packetfence_cluster
- name: Disable IPv6
  ansible.posix.sysctl:
    name: 'net.ipv6.conf.all.disable_ipv6'
    value: '1'
    state: 'present'

- name: Enable non local bind on IPv4
  ansible.posix.sysctl:
    name: 'net.ipv4.ip_nonlocal_bind'
    value: '1'
    state: 'present'

# include in place of import (dynamic evaluation)
- name: include distribution specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"
