galaxy_info:
  author: "Inverse inc <info@inverse.ca>"
  description: "Install PacketFence cluster"
  company: "Inverse inc"
  license: "GPL-3.0-only"
  min_ansible_version: 2.8

  platforms:
  - name: Debian
    versions:
    - bullseye
  - name: EL
    versions:
    - 8

  galaxy_tags:
    - packetfence
    - nac

dependencies: []
