---
### Generic
# we always want latest package to get:
# - latest nightly builds (devel)
# - latest maintenance patches (stable)
packetfence_install__pkg_state: latest

# default deployment is standalone
packetfence_install__cluster: False

### RedHat specific
packetfence_install__centos:
  repos:
    - packetfence

packetfence_install__rpm_key_url: http://inverse.ca/downloads/GPG_PUBLIC_KEY
packetfence_install__centos_release_pkg: packetfence-release
packetfence_install__centos_release_rpm: "http://packetfence.org/downloads/PacketFence/RHEL8/packetfence-release-11.0.el8.noarch.rpm"
packetfence_install__centos_packages:
  - packetfence

packetfence_install__rpm_replication_pkgs:
  - MariaDB-backup
  - socat

packetfence_install__centos_python_mysql_pkg: python3-PyMySQL

### Debian specific
packetfence_install__deb:
  repos:
    - debian/11.0

packetfence_install__apt_key_url: http://inverse.ca/downloads/GPG_PUBLIC_KEY
packetfence_install__deb_inverse_key_id: B022C48D3D6373D7FC256A8CCB2D3A2AA0030E2C
packetfence_install__deb_sources_dir: /etc/apt/sources.list.d
packetfence_install__deb_packages:
  - packetfence

packetfence_install__deb_replication_pkgs:
  - mariadb-backup

packetfence_install__shell_rc_file: /root/.bashrc

### database
packetfence_install__database_db: pf
packetfence_install__database_root_user: root
packetfence_install__database_root_pass: secret
packetfence_install__database_pass: secret
packetfence_install__database_default_user: 'pf'
packetfence_install__database_users:
  - name: '{{ packetfence_install__database_default_user }}'
    password: "{{ packetfence_install__database_pass }}"
    priv: "pf.*:SELECT,INSERT,UPDATE,DELETE,LOCK TABLES,EXECUTE,CREATE TEMPORARY TABLES/mysql.proc:SELECT/pf.radius_nas:DROP"
    append_privs: no
    host: "localhost"
  - name: '{{ packetfence_install__database_default_user }}'
    password: "{{ packetfence_install__database_pass }}"
    priv: "pf.*:SELECT,INSERT,UPDATE,DELETE,LOCK TABLES,EXECUTE,CREATE TEMPORARY TABLES/mysql.proc:SELECT/pf.radius_nas:DROP"
    append_privs: no
    host: "%"

### configurator
# default value is different from PF defaults
# but we assume that when we use Ansible, we don't use configurator
packetfence_install__configurator_status: 'disabled'

# interfaces
packetfence_install__mgmt_interface:
  id: "{{ ansible_default_ipv4['interface'] }}"
  ip: "{{ ansible_default_ipv4['address'] }}"
  mask: "{{ ansible_default_ipv4['netmask'] }}"
  type: management

# fingerbank settings
packetfence_install__fingerbank_setting:
  upstream:
    api_key: ''

### PacketFence configuration
packetfence_install__configuration:

      - name: 'pf.conf'
        sections:

          - name: 'database'
            settings:

              - name: 'pass'
                value: '{{ packetfence_install__database_pass }}'

          - name: 'advanced'
            settings:

              - name: 'configurator'
                value: '{{ packetfence_install__configurator_status }}'

          - name: "interface {{ packetfence_install__mgmt_interface['id'] }}"
            settings:

              - name: 'ip'
                value: "{{ packetfence_install__mgmt_interface['ip'] }}"

              - name: 'mask'
                value: "{{ packetfence_install__mgmt_interface['mask'] }}"

              - name: 'type'
                value: "{{ packetfence_install__mgmt_interface['type'] }}"

      - name: 'pfconfig.conf'
        sections:

          - name: 'general'
            settings:

              - name: 'backend'
                value: 'mysql'

          - name: 'mysql'
            settings:

              - name: 'host'
                value: 'localhost'

              - name: 'user'
                value: '{{ packetfence_install__database_default_user }}'

              - name: 'pass'
                value: '{{ packetfence_install__database_pass }}'

              - name: 'db'
                value: '{{ packetfence_install__database_db }}'

              - name: 'port'
                value: '3306'

              - name: 'table'
                value: 'keyed'
