---
- name: POST {{ pf_api_login }}
  uri:
    url: "https://{{ ansible_default_ipv4['address'] }}:{{ pf_api_port}}/{{ pf_api_login }}"
    method: POST
    follow_redirects: safe
    validate_certs: no
    return_content: yes
    body_format: json                     # automatically set Content-Type header to JSON
    body: "{{ pf_admin_credentials | to_json }}"
  register: api_token_result

- name: register token in a fact
  set_fact:
    pf_api_token: "{{ api_token_result.json.token }}"
  
- name: "{{ item.method }} {{ item.route }}"
  uri:
    url: "https://{{ ansible_default_ipv4['address'] }}:{{ pf_api_port}}/{{ item.route }}"
    method: "{{ item.method }}"
    follow_redirects: safe
    validate_certs: no
    return_content: yes
    body_format: json
    HEADER_Authorization: "{{ pf_api_token }}"
    body: "{{ item.body | to_json }}"
  loop: "{{ pf_api_calls }}"