---
- name: POST {{ pf_api_login }} (to get token)
  uri:
    url: "https://{{ ansible_default_ipv4['address'] }}:{{ pf_api_port}}/{{ pf_api_login }}"
    method: POST
    follow_redirects: safe
    validate_certs: no
    return_content: yes
    body_format: json                     # automatically set Content-Type header to JSON
    body: "{{ pf_admin_credentials | to_json }}"
  register: api_login

#- name: POST {{ pf_api_config_interface }}

- name: PATCH {{ pf_api_config['base'] }}