---
- name: set packetfence password in db in pf.conf
  ini_file:
    path: "{{ pf_conf_dir }}/pf.conf"
    section: database
    option: pass
    value: "{{ pf_database_pass }}"
    state: present
    mode: 0664
    owner: "{{ pf_user }}"
    group: "{{ pf_group }}"
    no_extra_spaces: yes
  register: pf_password_result

- name: set packetfence password in db in pfconfig.conf
  ini_file:
    path: "{{ pf_conf_dir }}/pfconfig.conf"
    section: mysql
    option: pass
    value: "{{ pf_database_pass }}"
    state: present
    mode: 0664
    owner: "{{ pf_user }}"
    group: "{{ pf_group }}"
    no_extra_spaces: yes
  register: pfconfig_password_result
  
- name: define mgmt interface in pf.conf
  ini_file:
    path: "{{ pf_conf_dir }}/pf.conf"
    section: "interface {{ pf_mgmt_interface['id'] }}"
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    mode: 0664
    owner: "{{ pf_user }}"
    group: "{{ pf_group }}"
    no_extra_spaces: yes
  loop:
    - name: ip
      value: "{{ pf_mgmt_interface['ip'] }}"
    - name: mask
      value: "{{ pf_mgmt_interface['mask'] }}"
    - name: type
      value: "{{ pf_mgmt_interface['type'] }}"
    
# to take new DB password into account
- name: restart packetfence-config service
  service:
    name: packetfence-config
    state: restarted
  when: (pf_password_result or pfconfig_password_result) is changed
  
- name: update default admin password in db through pfperl-api
  command:
  args:
    argv:
      - "{{ pf_perlapi_cmd }}"
      - get
      - "-M"
      - PATCH
      - "{{ pf_api_user }}/{{ pf_admin_user['pid'] }}/password"
      - "-c"
      - "{{ pf_admin_user | to_json }}"
  register: api_user_result
  # failed when status is different from 200
  # pfperl-api always return rc=0
  failed_when: (api_user_result['stdout'] | from_json ).status != 200

- name: fix permissions on pf files
  command: "{{ pf_pfcmd }} fixpermissions"
  when: pkg_update is changed

- name: clear the backend of pfconfig
  command: "{{ pf_pfcmd }} pfconfig clear_backend"
  when: pkg_update is changed

- name: restart packetfence-config service
  service:
    name: packetfence-config
    state: restarted
  when: pkg_update is changed

- name: restart pf services
  command: "{{ pf_pfcmd }} service pf restart"
  when: pkg_update is changed

# copy pf-release to currently-at
- name: ensure currently-at file is set
  copy:
    src: "{{ pf_conf_dir }}/pf-release"
    remote_src: yes
    dest: "{{ pf_conf_dir }}/currently-at"
    owner: "{{ pf_user }}"
    group: "{{ pf_group }}"
    mode: preserve

- name: check end of configurator
  uri:
    url: "https://{{ ansible_default_ipv4['address'] }}:{{ pf_webadmin_port }}"
    return_content: yes
    follow_redirects: safe
    validate_certs: no
  register: webadmin_homepage
  until: "'Administrator - PacketFence' in webadmin_homepage['content']"
  retries: 6
  delay: 10