---
# code from ansible-role-openio-galera (secure_install.yml)
- name: check password
  command: mysql -e ';'
  register: _check_password
  changed_when: false
  failed_when: false

- name: set the mariadb root password
  command: 'mysqladmin -u root password "{{ pf_database_root_pass }}"'
  changed_when: false
  when: _check_password.rc == 0
  ignore_errors: "{{ ansible_check_mode }}"

- name: delete anonymous connections
  mysql_user:
    login_user: "{{ pf_database_root_user }}"
    login_password: "{{ pf_database_root_pass }}"
    login_unix_socket: "{{ pf_database_socket }}"
    name: ""
    state: absent
  ignore_errors: "{{ ansible_check_mode }}"

- name: secure the mariadb root user for localhost
  mysql_user:
    login_user: "{{ pf_database_root_user }}"
    login_password: "{{ pf_database_root_pass }}"
    login_unix_socket: "{{ pf_database_socket }}"
    name: "{{ pf_database_root_user }}"
    host: "{{ item }}"
  loop:
    - ::1
    - 127.0.0.1
  ignore_errors: "{{ ansible_check_mode }}"

- name: remove the mariadb test database
  mysql_db:
    db: test
    login_user: "{{ pf_database_root_user }}"
    login_password: "{{ pf_database_root_pass }}"
    login_unix_socket: "{{ pf_database_socket }}"
    state: absent
  ignore_errors: "{{ ansible_check_mode }}"

- name: create pf db
  mysql_db:
    db: pf
    login_user: "{{ pf_database_root_user }}"
    login_password: "{{ pf_database_root_pass }}"
    login_unix_socket: "{{ pf_database_socket }}"
    state: present

- name: create pf user in db
  mysql_user:
    login_user: "{{ pf_database_root_user }}"
    login_password: "{{ pf_database_root_pass }}"
    login_unix_socket: "{{ pf_database_socket }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    append_privs: "{{ item.append_privs }}"
    host: "{{ item.host }}"
    state: present
  loop: "{{ pf_database_users }}"

# - name: create pf tables
# see https://github.com/open-io/ansible-role-openio-galera/blob/19.04/tasks/postinstall.yml
#   mysql_db:
#     db: pf
#     login_user: "{{ pf_database_root_user }}"
#     login_password: "{{ pf_database_root_pass }}"
#     state: present
#     login_unix_socket: "{{ pf_database_socket }}"

# not mandatory for now but todo
#- name: change admin password in db
  