---
# tasks file for pf.install
- name: import distribution specific variables
  include_vars: "{{ ansible_os_family|lower }}.yml"

# include in place of import (dynamic evaluation)
- name: include distribution specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: include utils tasks
  include_tasks: utils.yml
  tags: utils

- name: include database tasks
  include_tasks: db.yml
  tags: db
  
- name: include configurator tasks
  include_tasks: configurator.yml
  tags: configurator