---
# tasks file for pf.install
- name: import distribution specific variables
  include_vars: "{{ ansible_os_family|lower }}.yml"

# include in place of import (dynamic evaluation)
- name: include distribution specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"

# only if configurator step has been finished
# this is to update simply devel machines
- name: restart pf services
  command: "{{ pf_pfcmd }} service pf restart"
  args:
    removes: "{{ pf_currently_at_file }}"
  register: pfcmd_result
  when: pkg_update is changed

- name: print result of pfcmd
  debug:
    msg: "{{ pfcmd_result.stdout_lines }}"
    verbosity: 2
  when: pfcmd_result is defined

- name: include utils tasks
  include_tasks: utils.yml
  tags: utils

- name: include configurator tasks
  include_tasks: configurator.yml
  tags: configurator