---
- name: Install the PacketFence repo
  yum:
    name: "{{ centos_pf_release_rpm }}"
    state: present

- name: Update the PacketFence repo
  yum:
    name: "{{ centos_pf_release_pkg }}"
    enablerepo: "{{ centos['repo'] }}"
    state: latest

# NLTM wrapper is not a dependence of packetfence
- name: Install PacketFence and NTLM wrapper from the repo
  yum:
    name: "{{ centos_pf_packages }}"
    enablerepo: "{{ centos['repo'] }}"
    state: latest
    update_cache: yes

# to be replaced by InSpec tests
# - name: Check PF package
#   yum:
#     list: packetfence
#   register: pf_package

# - name: Set facts
#   set_fact:
#     pkg_name: "{{ pf_package.results[0].name }}"
#     pkg_version: "{{ pf_package.results[0].version }}.{{ pf_package.results[0].release }}"
#     pkg_state: "{{ pf_package.results[0].yumstate }}"

# # in particular distribution in case of system upgrade
# - name: recall setup module to refresh facts
#   setup:
#     filter: ansible_distribution*
    
# - name: Print PF installed
#   debug:
#     msg: "{{ pkg_name }} {{ pkg_version }} {{ pkg_state }} on {{ ansible_distribution }} {{ ansible_distribution_version }}"
  