---
- name: install dependencies for next tasks and PacketFence install
  apt:
    name: '{{ packetfence_common__deb_deps_pkgs }}'
    state: present
    update_cache: yes

- name: ensure systemd-networkd is installed
  stat:
    path: /lib/systemd/system/systemd-networkd.service
  register: packetfence_common__register_deb_systemd_networkd

- name: ensure systemd-networkd is disabled to manage network with ifupdown
  service:
    name: systemd-networkd
    state: stopped
    enabled: no
  when: packetfence_common__register_deb_systemd_networkd.stat.exists

- name: ensure systemd-resolved is installed
  stat:
    path: /lib/systemd/system/systemd-resolved.service
  register: packetfence_common__register_deb_systemd_resolved

- name: ensure systemd-resolved is disabled to let pfdns start
  service:
    name: systemd-resolved
    state: stopped
    enabled: no
  when: packetfence_common__register_deb_systemd_resolved.stat.exists
  register: packetfence_common__register_deb_systemd_resolved_disabled

- name: configure DNS resolution using ansible facts in /etc/resolv.conf
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: packetfence_common__register_deb_systemd_resolved_disabled is changed
