---
- name: import distribution specific variables
  include_vars: "{{ ansible_os_family|lower }}.yml"

# include in place of import (dynamic evaluation)
- name: include distribution specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: ensure iproute package is installed to get network informations
  package:
    name: "{{ packetfence_common__iproute_pkg }}"
    state: present
  register: packetfence_common__register_pkg_iproute

- name: recall setup module to refresh ansible_default_ipv4 facts
  setup:
    filter: ansible_default_ipv4*
  when: packetfence_common__register_pkg_iproute is changed

- name: recall setup module to refresh ansible_eth facts
  setup:
    filter: ansible_eth*
  when: packetfence_common__register_pkg_iproute is changed

- name: ensure python-passlib package is installed for htpasswd sources
  package:
    name: "{{ packetfence_common__passlib_pkg }}"
    state: present
