---
# defaults file for install-pf
centos:
  repo: packetfence

# list, see packetfence.list.j2
deb:
  repos:
    - debian

shell_rc_file: /root/.bashrc

### database
pf_database_db: pf
pf_database_root_user: root
pf_database_root_pass: secret
pf_database_pass: secret
pf_database_users:
  - name: pf
    password: "{{ pf_database_pass }}"
    encrypted: yes
    priv: "pf.*:SELECT,INSERT,UPDATE,DELETE,LOCK TABLES,EXECUTE"
    append_privs: no
    host: "localhost"
  - name: pf
    password: "{{ pf_database_pass }}"
    encrypted: yes
    priv: "pf.*:SELECT,INSERT,UPDATE,DELETE,LOCK TABLES,EXECUTE"
    append_privs: no
    host: "%"
  - name: pf
    password: "{{ pf_database_pass }}"
    encrypted: yes
    priv: "mysql.proc:SELECT"
    append_privs: yes
    host: "localhost"
  - name: pf
    password: "{{ pf_database_pass }}"
    encrypted: yes
    priv: "mysql.proc:SELECT"
    append_privs: yes
    host: "%"
  - name: pf
    password: "{{ pf_database_pass }}"
    encrypted: yes
    priv: "pf.radius_nas:DROP"
    append_privs: yes
    host: "localhost"
  - name: pf
    password: "{{ pf_database_pass }}"
    encrypted: yes
    priv: "pf.radius_nas:DROP"
    append_privs: yes
    host: "%"

### configurator
# interfaces
pf_interfaces:
  - id: "{{ ansible_default_ipv4['interface'] }}"
    ip: "{{ ansible_default_ipv4['address'] }}"
    mask: "{{ ansible_default_ipv4['netmask'] }}"
    type: management,portal

### users
pf_admin_user:
  pid: admin
  password: secret
    
