---
### RedHat specific
centos:
  repo: packetfence

centos_pf_release_pkg: packetfence-release
centos_pf_release_rpm: "http://packetfence.org/downloads/PacketFence/RHEL7/x86_64/RPMS/{{ centos_pf_release_pkg }}-1.2-7.el7.noarch.rpm"
centos_pf_packages:
  - packetfence
  - packetfence-ntlm-wrapper

centos_python_mysql_pkg: python2-PyMySQL

### Debian specific
# list, see packetfence.list.j2
deb:
  repos:
    - debian
deb_inverse_key_id: FE9E84327B18FF82B0378B6719CDA6A9810273C4
deb_sources_dir: /etc/apt/sources.list.d
deb_pf_packages:
  - packetfence

shell_rc_file: /root/.bashrc

### database
pf_database_db: pf
pf_database_root_user: root
pf_database_root_pass: secret
pf_database_pass: secret
pf_database_users:
  - name: pf
    password: "{{ pf_database_pass }}"
    priv: "pf.*:SELECT,INSERT,UPDATE,DELETE,LOCK TABLES,EXECUTE/mysql.proc:SELECT/pf.radius_nas:DROP"
    append_privs: no
    host: "localhost"
  - name: pf
    password: "{{ pf_database_pass }}"
    priv: "pf.*:SELECT,INSERT,UPDATE,DELETE,LOCK TABLES,EXECUTE/mysql.proc:SELECT/pf.radius_nas:DROP"
    append_privs: no
    host: "%"

### configurator
# interfaces
pf_mgmt_interface:
  id: "{{ ansible_default_ipv4['interface'] }}"
  ip: "{{ ansible_default_ipv4['address'] }}"
  mask: "{{ ansible_default_ipv4['netmask'] }}"
  type: management

### users
pf_admin_user:
  pid: admin
  password: secret

# to use API
pf_admin_credentials:
  username: "{{ pf_admin_user['pid'] }}"
  password: "{{ pf_admin_user['password'] }}"