---
# defaults file for install-pf
centos:
  repo: packetfence

# list, see packetfence.list.j2
deb:
  repos:
    - debian

shell_rc_file: /root/.bashrc

### database
pf_database_root_user: root
pf_database_root_pass: secret

### configurator
# database
pf_database_pass: secret

# interfaces
pf_interfaces:
  - id: "{{ ansible_default_ipv4['interface'] }}"
    ip: "{{ ansible_default_ipv4['address'] }}"
    mask: "{{ ansible_default_ipv4['netmask'] }}"
    type: management,portal

